<?xml version="1.0"?>
<robot name="urdf_project_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="plugin.xacro" />

    <material name="blue">
        <color rgba="0 0 0.5 1" />
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.5 0 1" />
    </material>

    <material name="yellow">
        <color rgba="1 1 0 1" />
    </material>

    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>

    <gazebo reference="right_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="left_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <gazebo reference="arm_base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="forearm_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="hand_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <xacro:property name="base_length" value="0.6" />
    <xacro:property name="base_width" value="0.4" />
    <xacro:property name="base_height" value="0.2" />
    <xacro:property name="wheel_radius" value="0.1" />
    <xacro:property name="wheel_length" value="0.05" />

    <xacro:macro name="box_inertia" params="m l w h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}" />
            <mass value="${m}" />
            <inertia ixx="${2 * (m/12) * (h*h + l*l)}" ixy="0" ixz="0"
                     iyy="${2 * (m/12) * (w*w + l*l)}" iyz="0"
                     izz="${2 * (m/12) * (w*w + h*h)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}" />
            <mass value="${m}" />
            <inertia ixx="${2 * (m/12) * (3*r*r + h*h)}" ixy="0" ixz="0"
                     iyy="${2 * (m/12) * (3*r*r + h*h)}" iyz="0"
                     izz="${2 * (m/2) * (r*r)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}" />
            <mass value="${m}" />
            <inertia ixx="${2 * (2/5) * m * r * r}" ixy="0" ixz="0"
                     iyy="${2 * (2/5) * m * r * r}" iyz="0"
                     izz="${2 * (2/5) * m * r * r}" />
        </inertial>
    </xacro:macro>

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
        <xacro:box_inertia m="5" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        <collision>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry> 
        </collision>
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="grey" />
            </visual>
            <xacro:cylinder_inertia m="1" r="${wheel_radius}" h="${wheel_length}"
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <collision>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="grey" />
        </visual>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius / 2.0}" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <sphere radius="${wheel_radius / 2.0}" />
            </geometry>
        </collision>
    </link>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="0.1 0.1 0.02" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <xacro:box_inertia m="0.2" l="0.1" w="0.1" h="0.02" xyz="0 0 0" rpy="0 0 0" />
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.1 0.1 0.02" />
            </geometry>
        </collision>
    </link>

    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="0.3" />
            </geometry>
            <origin xyz="0 0 0.15" rpy="0 0 0" />
            <material name="yellow" />
        </visual>
        <xacro:cylinder_inertia m="0.3" r="0.02" h="0.3" xyz="0 0 0.15" rpy="0 0 0" />
        <collision>
            <origin xyz="0 0 0.15" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.02" length="0.3" />
            </geometry>
        </collision>
    </link>

    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="0.02" length="0.3" />
            </geometry>
            <origin xyz="0 0 0.15" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <xacro:cylinder_inertia m="0.3" r="0.02" h="0.3" xyz="0 0 0.15" rpy="0 0 0" />
        <collision>
            <origin xyz="0 0 0.15" rpy="0 0 0" />
            <geometry>
                <cylinder radius="0.02" length="0.3" />
            </geometry>
        </collision>
    </link>

    <joint name="caster_joint" type="fixed">
        <origin xyz="${base_length / 4.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="caster_wheel_link" />
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="0.25 0 ${base_height + 0.01}" rpy="0 0 0" />
    </joint>

    <joint name="forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0 " />
        <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="1.0" />
    </joint>

    <joint name="hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 0.3" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="1000.0" lower="-1.57" upper="1.57" velocity="1.0" />
    </joint>
    
</robot>
        